### ISSUE TITLE
숙련 주차 개인과제 피드백 - 정영훈 튜터

### ISSUE THREAD

**Issue by jyh7a** [Areum123123/sparta_resume#4]
개인과제 하느라 수고 많으셨습니다. 

커밋이나 README 도 잘 작성해 주셨습니다. 
transaction 은 처음 배우는 내용이라 아마 많이 어려웠다고 생각이 듭니다. 
먼저 `transaction 필요한 이유`를 검색해서 왜 트랜잭션이 필요한지 이유를 알고 
구현을 해주시면됩니다. 해설영상을 참고해서 왜? 어떤식으로? transaction을 하는지 숙지해주세요. 

아래는 코드 피드백입니다. 

--- 

### 1. API 명세서 수정
기본적으로 명세서는 잘 작성 하였습니다. 아래 몇가지 수정 사항을 참고해서 수정해 주세요.
1. 리소스는 북수 형태로 표현 
예) /api/user -> /api/users
2. 내정보 조회시 인증 탭(access token)추가, req header 토큰 값 명시 
예) req header : authorization: Bearer accessToken
3. 이제 다른 로그인 인증이 필요한 api에게도 인증 탭과 req header 를 추가해 주세요.

<br/>

---

<br/>

### 2. ERD 수정
ERD도 잘 작성 하였습니다. 
유저는 이력서를 여러개 가질수 있으니 1:N으로 잘 표현 하였습니다. 
이제 이력서의 기록(로그)를 어떻게 관리할지 생각해 봅시다.
이력서가 수정되거나, 이력서의 상태가 변경되면 이 행동을 이력서 테이블에 컬럼을 추가해서 관리할지 
아니면 이력서 로그 테이블을 만들어서 관리할지 생각해 보시길 바랍니다.

<br/>

---

<br/>

### 3. 이메일 검증 로직 함수 or 미들웨어로 분리 
https://github.com/Areum123123/sparta_resume/blob/32d3c22cfd229f62f02b73bf9704c056da986eb4/src/routers/users.routers.js#L47-L48
이메일 검증로직이 동일하게 계속 사용되고 있습니다. 
이런 로직은 함수나 미들웨어로 분리해서 유지보수에 편하게 만들어 주는것이 중요합니다.

```javascript
// 이메일 형식 검증 함수 
const validateEmailFormat = (email) => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
};

```

<br/>

---

<br/>

### 4. 오타 수정
라우터에 작성한 함술을 대부분 잘 작성되었습니다. 
이력서 상세 조회에서는 오타가 조금 있습니다. 
APPLICANT 와 상수들도 이런 오타를 줄이기 위해서 constants 폴더를 만들고 상수를 관리하면 이런 오류를 방지할 수 있습니다. 
vscode에서는 Code Spell Checker 익스텐션을 설치하면 오타를 찾는데 매우 도움이 됩니다.

https://github.com/Areum123123/sparta_resume/blob/32d3c22cfd229f62f02b73bf9704c056da986eb4/src/routers/resumes.router.js#L100
1. APPLICATN - > APPLICANT

https://github.com/Areum123123/sparta_resume/blob/32d3c22cfd229f62f02b73bf9704c056da986eb4/src/routers/resumes.router.js#L112
2. :await prisma.resumes.findFirst({ -> await prisma.resumes.findFirst({

<br/>

---

<br/>

### 5. 선택 기능 구현 
이제는 이력서 로그를 볼 수 있도록 ResumeLog 테이블도 만들고 
로그를 생성할때 transaction을 사용 하도록 코드를 작성해주세요. 
해설영상을 보면서 나머지 기능들을 차례대로 구현해보시고. 
오류나 이해안되는 부분은 동료분들 또는 튜터님들에게 와서 질문주세요!

**Comment by Areum123123** [comment]
-growth branch-

1. API 명세서 수정
(1) 완료✔️
(2) 완료✔️
(3) 완료✔︎

4. 오타 수정
(1)APPLICANT 수정완료✔︎
(2) 이력서 상세조회 삼항 연산자 사용해서 (:) 사용 / 사용에 관련해서 튜터님께 여쭤보기.  △

**Comment by jyh7a** [comment]
2. 오타 수정
(1)APPLICANT 수정완료 ✅
(2) 이력서 상세조회 삼항 연산자 사용해서 (:) 사용 / 사용에 관련해서 튜터님께 여쭤보기. △ -
👉 3항 연산자를 사용한 부분을 제가 실수로 잘못 보았습니다. 
  3항 연산자는 짧고 단순한 조건에서 유용하지만 복잡한 논리를 처리할 때는 코드의 가독성 떨어지기 떄문에 
  if 문으로 처리하면 조금더 가독성 좋은 코드를 작성할 수 있습니다. 
  현재 3항 연사자를 사용해도 문제는 없습니다.

**Comment by Areum123123** [comment]
확인해  주셔서 감사합니다. :)
